name: Daily Run

on:
  workflow_dispatch:
  push:
    
jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      EDM_DATA: ${{ secrets.EDM_DATA }}
      AWS_S3_ENDPOINT: ${{ secrets.DO_S3_ENDPOINT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.DO_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET: edm-recipes
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9' 
          
      - name: Install Dependencies
        run: python3 -m pip install -r requirements.txt     
      
      - name: Run
        run: python3 -m checkboooknyc.capital_spending
